---
- name: rebuild buildroot
  command: "{{ atomic_reactor_rpm.buildroot_cmd }}"

- name: tag pulled image
  command: docker tag -f {{ atomic_reactor_pull.registry }}/{{ atomic_reactor_pull.image }} {{ atomic_reactor_tag }}

- name: tag for internal registry
  command: docker tag -f {{ atomic_reactor_tag }} {{ item }}
  with_items: "{{ atomic_reactor_push_to }}"

- name: push to internal registry
  command: docker push {{ item }}
  with_items: "{{ atomic_reactor_push_to }}"
